### ISSUE TITLE
安装插件后热点IP仍然随机

### ISSUE THREAD

**Issue by NpTIme** [XhyEax/SoftApHelper#26] opened 2024-06-30 05:19 UTC
机型: Redmi Note 12 Turbo (Marble)
系统: LineageOS 21
[marble.zip](https://github.com/user-attachments/files/16043282/marble.zip)
其中Lsposed用的是 [Lsposed-Mod](https://github.com/mywalkb/LSPosed_mod)
插件版本为v1.091-192.168.43.1和v1.091-192.168.1.1,两个版本都经过测试无法工作

**Comment by XhyEax** [comment] 2024-06-30 05:55
安卓14？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月30日(周日) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 安装插件后热点IP仍然随机 (Issue #26)




 
机型: Redmi Note 12 Turbo (Marble)
 系统: LineageOS 21
 marble.zip
 其中Lsposed用的是 Lsposed-Mod
 插件版本为v1.091-192.168.43.1和v1.091-192.168.1.1,两个版本都经过测试无法工作
 Screenshot_20240630-131142_Settings.png (view on web)
 Screenshot_20240630-130617_Termux.png (view on web)

**Comment by NpTIme** [comment] 2024-07-01 00:57
> 安卓14？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月30日(周日) 中午1:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [XhyEax/SoftApHelper] 安装插件后热点IP仍然随机 (Issue #26) 机型: Redmi Note 12 Turbo (Marble) 系统: LineageOS 21 marble.zip 其中Lsposed用的是 Lsposed-Mod 插件版本为v1.091-192.168.43.1和v1.091-192.168.1.1,两个版本都经过测试无法工作 Screenshot_20240630-131142_Settings.png (view on web) Screenshot_20240630-130617_Termux.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

reply：对

**Comment by XhyEax** [comment] 2024-07-02 14:28
看看LSPosed的模块日志，里面是否有报错信息

**Comment by NpTIme** [comment] 2024-07-09 04:26
> 看看LSPosed的模块日志，里面是否有报错信息

我不到啊
以下是我找到的有关信息
***
[ 2024-06-30T12:58:41.312     1000:  2070:  2070 I/LSPosed         ] Loading xposed for system/1000
[ 2024-06-30T12:58:41.323     1000:  2070:  2070 I/LSPosed-Bridge  ] Loading legacy module com.xhy.xp.softaphelper from /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk
[ 2024-06-30T12:58:41.325     1000:  2070:  2070 I/LSPosed-Bridge  ]   Loading class com.xhy.xp.softaphelper.MainHook
[ 2024-06-30T12:58:41.814        0:  1456:  1456 I/LSPosedService  ] service package is not started, wait 1s.
[ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] ** late_start service mode running
[ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] * Running service.d scripts
[ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] * Running module service scripts
[ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] cu_jank_detector: exec [service.sh]
[ 2024-06-30T12:58:42.049        0:  1440:  1442 I/Magisk          ] WorkSettingPro: exec [service.sh]
[ 2024-06-30T12:58:42.057        0:  1440:  1442 I/Magisk          ] RescueBrick: exec [service.sh]
[ 2024-06-30T12:58:42.064        0:  1440:  1442 I/Magisk          ] zygisk_lsposed: exec [service.sh]
[ 2024-06-30T12:58:42.069        0:  1440:  1442 I/Magisk          ] sffflbr: exec [service.sh]
[ 2024-06-30T12:58:42.814        0:  1456:  1456 I/LSPosedService  ] service package is not started, wait 1s.
[ 2024-06-30T12:58:43.815        0:  1456:  1456 I/LSPosedService  ] service package is not started, wait 1s.
[ 2024-06-30T12:58:44.817     1000:  2070:  2690 I/LSPosed Bridge  ] binder received
[ 2024-06-30T12:58:44.817        0:  1456:  1456 I/LSPosedService  ] sent service to bridge
[ 2024-06-30T12:58:44.873        0:  1456:  1962 I/LSPosedService  ] manager is not installed
[ 2024-06-30T12:58:44.878        0:  1456:  1900 I/LSPosedService  ] manager is not installed
[ 2024-06-30T12:58:46.083     1073:  3481:  3481 I/LSPosed         ] Loading xposed for com.android.networkstack.process/1073
[ 2024-06-30T12:58:46.088     1073:  3481:  3481 I/LSPosed-Bridge  ] Loading legacy module com.xhy.xp.softaphelper from /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk
[ 2024-06-30T12:58:46.089     1073:  3481:  3481 I/LSPosed-Bridge  ]   Loading class com.xhy.xp.softaphelper.MainHook
[ 2024-06-30T12:58:48.263     1000:  2255:  2255 F/libc            ] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 2255 (marbleLightSens), pid 2255 (marbleLightSens)
***

***
07-09 12:15:18.346 31647 31660 W m.android.shell: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk' with 1 weak references
***

***
07-09 12:16:46.040 31647 31660 W m.android.shell: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk' with 1 weak references
***

我就只找到这一点
以下为lsposed导出的完整日志文件
[LSPosed_2024-07-09T12_16_42.955113.zip](https://github.com/user-attachments/files/16138006/LSPosed_2024-07-09T12_16_42.955113.zip)

**Comment by XhyEax** [comment] 2024-07-09 06:53
没看到有相关报错，作用域勾选系统框架了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月9日(周二) 中午12:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 安装插件后热点IP仍然随机 (Issue #26)




  
看看LSPosed的模块日志，里面是否有报错信息
  
我不到啊
 以下是我找到的有关信息
 
 
[ 2024-06-30T12:58:41.312     1000:  2070:  2070 I/LSPosed         ] Loading xposed for system/1000
 [ 2024-06-30T12:58:41.323     1000:  2070:  2070 I/LSPosed-Bridge  ] Loading legacy module com.xhy.xp.softaphelper from /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk
 [ 2024-06-30T12:58:41.325     1000:  2070:  2070 I/LSPosed-Bridge  ]   Loading class com.xhy.xp.softaphelper.MainHook
 [ 2024-06-30T12:58:41.814        0:  1456:  1456 I/LSPosedService  ] service package is not started, wait 1s.
 [ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] ** late_start service mode running
 [ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] * Running service.d scripts
 [ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] * Running module service scripts
 [ 2024-06-30T12:58:42.042        0:  1440:  1442 I/Magisk          ] cu_jank_detector: exec [service.sh]
 [ 2024-06-30T12:58:42.049        0:  1440:  1442 I/Magisk          ] WorkSettingPro: exec [service.sh]
 [ 2024-06-30T12:58:42.057        0:  1440:  1442 I/Magisk          ] RescueBrick: exec [service.sh]
 [ 2024-06-30T12:58:42.064        0:  1440:  1442 I/Magisk          ] zygisk_lsposed: exec [service.sh]
 [ 2024-06-30T12:58:42.069        0:  1440:  1442 I/Magisk          ] sffflbr: exec [service.sh]
 [ 2024-06-30T12:58:42.814        0:  1456:  1456 I/LSPosedService  ] service package is not started, wait 1s.
 [ 2024-06-30T12:58:43.815        0:  1456:  1456 I/LSPosedService  ] service package is not started, wait 1s.
 [ 2024-06-30T12:58:44.817     1000:  2070:  2690 I/LSPosed Bridge  ] binder received
 [ 2024-06-30T12:58:44.817        0:  1456:  1456 I/LSPosedService  ] sent service to bridge
 [ 2024-06-30T12:58:44.873        0:  1456:  1962 I/LSPosedService  ] manager is not installed
 [ 2024-06-30T12:58:44.878        0:  1456:  1900 I/LSPosedService  ] manager is not installed
 [ 2024-06-30T12:58:46.083     1073:  3481:  3481 I/LSPosed         ] Loading xposed for com.android.networkstack.process/1073
 [ 2024-06-30T12:58:46.088     1073:  3481:  3481 I/LSPosed-Bridge  ] Loading legacy module com.xhy.xp.softaphelper from /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk
 [ 2024-06-30T12:58:46.089     1073:  3481:  3481 I/LSPosed-Bridge  ]   Loading class com.xhy.xp.softaphelper.MainHook
 [ 2024-06-30T12:58:48.263     1000:  2255:  2255 F/libc            ] Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 2255 (marbleLightSens), pid 2255 (marbleLightSens)
 
 
 
07-09 12:15:18.346 31647 31660 W m.android.shell: ApkAssets: Deleting an ApkAssets object ' and /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk' with 1 weak references
 
 
 
07-09 12:16:46.040 31647 31660 W m.android.shell: ApkAssets: Deleting an ApkAssets object ' and /data/app/~~5fu-np1ZwzQ3-ghMM-Vlvw==/com.xhy.xp.softaphelper-3iSZWa5Axb_R5blClZ34iw==/base.apk' with 1 weak references
 
 
我就只找到这一点
 以下为lsposed导出的完整日志文件
 LSPosed_2024-07-09T12_16_42.955113.zip

**Comment by NpTIme** [comment] 2024-07-16 03:45
> 看看LSPosed的模块日志，里面是否有报错信息

    勾选了![Screenshot_20240716-114502_Shell.png](https://github.com/user-attachments/assets/cfb3d941-91de-41d1-8a98-414a470cd97b)

**Comment by XhyEax** [comment] 2024-07-24 05:11
Duplicate of #25

**Closed** 2024-07-24 05:10 UTC

**Comment by XhyEax** [comment] 2024-07-24 05:12
已知问题，LineageOS 21固定不了ip。

**Comment by XhyEax** [comment] 2024-07-24 09:27
用最新版的LineageOS 21+LSPosed_mod，可以固定wifi和usb热点的ip。

**Comment by NpTIme** [comment] 2024-07-24 17:15
> 用最新版的LineageOS 21+LSPosed_mod，可以固定wifi和usb热点的ip。

实测新版lineageos21已修复该问题，谢谢
